# This rule is not used by the project qiskit-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the quantum.quantum.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: qiskit-operator
    app.kubernetes.io/managed-by: kustomize
  name: qiskitjob-editor-role
rules:
- apiGroups:
  - quantum.quantum.io
  resources:
  - qiskitjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - quantum.quantum.io
  resources:
  - qiskitjobs/status
  verbs:
  - get
